[package]
name = "integration_test"
version = "0.1.0"
authors = ["Steven Roose <steven@stevenroose.org>, Tobin C. Harding <me@tobin.cc>"]
edition = "2018"

[dependencies]
satpoint-jsonrpc = { path = "..", features = ["minreq_http"] }
lazy_static = "1.4.0"
log = "0.4"
backtrace = "0.3.50"
serde_json = { version = "1.0", features = ["raw_value"] }
